// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
  eth2Sidebar: [{ type: 'autogenerated', dirName: 'Block-Construction' }],
  stratagiesSidebar: [{ type: 'autogenerated', dirName: 'Stratagies' }],
  protocolSidebar: [{ type: 'autogenerated', dirName: 'Protocol' }],
};

module.exports = sidebars;
