// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: 'general' }],
  eth2Sidebar: [{ type: 'autogenerated', dirName: 'Block-Construction' }],
  strategiesSidebar: [{ type: 'autogenerated', dirName: 'Strategies' }],
  protocolSidebar: [{ type: 'autogenerated', dirName: 'Protocol' }],
};

module.exports = sidebars;